### ISSUE TITLE
btw it crashed when I pressed J to start lol

### ISSUE THREAD

**Issue by Legacy107** [sangpham2710/TypingTest#2]

**Comment by sangpham2710** [comment]
u know why, because u r retarded

Vào Th 3, 17 thg 3, 2020 vào lúc 08:55 Legacy107 <notifications@github.com>
đã viết:

**Comment by sangpham2710** [comment]
Goto my channel on Discord i wrote my readme there

**Comment by Legacy107** [comment]
uhhhh why not readme here lol

**Comment by Legacy107** [comment]
I wonder whos retarded ;)
cuz I am lol
